swagger: '2.0'
info:
  version: '1.0'
  title: helloService
  license:
    name: GPL
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
host: host1506728453.sisdis.infralabs.cs.ui.id
basePath: "/api"
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /hello:
    post:
      description: Hello
      tags:
        - helloBinding
      operationId: Hello
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/Request'
      responses:
        '200':
          description: 'OK'
          schema:
            $ref: '#/definitions/HelloResponse'
        '400':
          description: 'Bad Request'
          schema:
            $ref: '#/definitions/HelloErrorRequest'
        '404':
          description: "Not Found"
          schema:
            $ref: "#/definitions/NotFoundErrorRequest"
  /plusone/{val}:
    get:
      description: "Returns an incremented value"
      parameters:
      - name: "val"
        in: "path"
        description: "value that need to be incremented"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Plusoneret"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/NotFoundErrorRequest"
definitions:
  Request:
    title: request
    type: object
    properties:
      request:
        description: ''
        example: 'ardhi'
        type: string
    required:
      - request
  HelloResponse:
    title: response
    type: object
    properties:
      apiversion:
        description: ''
        example: 1
        type: integer
      count:
        description: ''
        example: 1
        type: integer
      currentvisit:
        description: ''
        example: '2018-10-09 03:28:52.454861'
        type: string
      response:
        description: ''
        example: 'Good Night, ardhi'
        type: string
    required:
      - response
  Plusoneret:
    title: plusoneret
    type: object
    properties:
      apiversion:
        description: ''
        example: 1
        type: integer
      plusoneret:
        description: ''
        example: 5
        type: integer
    required:
      - plusoneret
  HelloErrorRequest:
    title: helloerrorrequest
    type: object
    properties:
      detail:
        description: ''
        example: "'request' is a required property"
        type: string
      status:
        description: ''
        example: 400
        type: integer
      title:
        description: ''
        type: string
        example: 'Bad Request'
  
  NotFoundErrorRequest:
    title: notfounderrorrequest
    type: object
    properties:
      detail:
        description: ''
        example: 'The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.'
        type: string
      status:
        description: ''
        example: 404
        type: integer
      title:
        description: ''
        type: string
        example: 'Not Found'